workflows:
  ios-build-workflow:
    name: iOS Unsigned Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Set up local properties
        script: |
          echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Pre-generate Podfile and Inject Permission Macros
        script: |
          cd ios
          # Generujemy czysty Podfile
          flutter build ios --config-only
          
          # Wstrzykujemy makra GCC bezpośrednio do istniejącego bloku post_install
          sed -i '' "s/flutter_additional_ios_build_settings(target)/flutter_additional_ios_build_settings(target)\n      target.build_configurations.each do { |config| config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['\$(inherited)', 'PERMISSION_LOCATION=1', 'PERMISSION_SENSORS=1'] }/g" Podfile
      - name: Build iOS project without signing
        script: |
          flutter build ios --no-codesign --release
    artifacts:
      - build/ios/iphoneos/Runner.app