workflows:
  ios-build-workflow:
    name: iOS Unsigned Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Set up local properties
        script: |
          echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Pre-generate configuration and Force Manual Signing Style
        script: |
          # Generujemy konfigurację środowiska
          flutter build ios --config-only
          
          # 1. Wstrzykujemy makra uprawnień lokalizacji i ruchu dla iOS
          echo "GCC_PREPROCESSOR_DEFINITIONS =\$(inherited) PERMISSION_LOCATION=1 PERMISSION_SENSORS=1" >> ios/Flutter/Generated.xcconfig
          
          # 2. Przestawiamy projekt Xcode z automatu na tryb Manualny, by zignorował błąd o "Development Team"
          sed -i '' 's/CODE_SIGN_STYLE = Automatic;/CODE_SIGN_STYLE = Manual;/g' ios/Runner.xcodeproj/project.pbxproj
          sed -i '' 's/DevelopmentTeam = .*/DevelopmentTeam = "";/g' ios/Runner.xcodeproj/project.pbxproj
          sed -i '' 's/PROVISIONING_PROFILE_SPECIFIER = .*/PROVISIONING_PROFILE_SPECIFIER = "";/g' ios/Runner.xcodeproj/project.pbxproj
      - name: Build iOS project without signing
        script: |
          # Budujemy czysty, niepodpisany projekt
          flutter build ios --no-codesign --release
    artifacts:
      - build/ios/iphoneos/Runner.app