platform :ios, '13.0'

# Skrypt Fluttera ładujący pluginy
target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.expand_path(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    # Prawidłowa i czysta składnia wstrzykiwania makr do kompilacji:
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'PERMISSION_LOCATION=1', 'PERMISSION_SENSORS=1']
    end
  end
end